[package]
name = "lambda-listen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc="*"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
hound = "3.5.1"
string-interner = "0.15"
tree-sitter = "0.20"
tree-sitter-lambdalisten = { path = "tree-sitter-lambdalisten" }
typed-arena = "2.0.2"
num = "0.4"
indenter = "0.3"

[profile.release]
debug = true
