cargo-features = ["per-package-target"]

[package]
name = "clocky-runtime"
version = "0.1.0"
edition = "2021"
forced-target = "wasm32-unknown-unknown"

[lib]
crate-type = ["cdylib"]

[dependencies]
libm = "0.2.8"
bit-set = "0.5.3"
